// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package digitalgoods

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%.2f":     140,
	"%.2f EUR": 149,
	"A payment is on the way, but we're still waiting for the required amount of confirmations on the blockchain.": 1,
	"Account holder":            145,
	"Address":                   104,
	"All Services and Projects": 118,
	"Amount":                    138,
	"As soon as your payment arrives, your voucher codes are shown. In the unlikely case that your goods have become sold out in the meantime, your codes will appear as soon as they are back in stock.": 98,
	"Australian dollars":                49,
	"Austria":                           15,
	"BIC (if required)":                 147,
	"Bank Transfer to our SEPA Account": 48,
	"Bank name (if required)":           148,
	"Belgium":                           16,
	"Bookmark this page or save its address in another way. You will need it to access your goods.": 95,
	"Bookmark your order. You will need it to access your goods.":                                   72,
	"Bulgaria":      17,
	"Bulgarian lev": 50,
	"Buy":           88,
	"Buy coupons, voucher codes and gift cards for privacy services and pay anonymously with Monero, Bitcoin or cash letter. SEPA Bank transfer is also available.": 68,
	"Canadian dollars":              51,
	"Cancellation Policy":           114,
	"Cash":                          47,
	"Cash by mail in 20 currencies": 115,
	"Cash in Foreign Currency":      46,
	"Cash: Send cash (we accept 20 currencies) to our office in Germany. We shred the letter after processing.": 76,
	"Chinese renminbi": 53,
	"Click to copy":    96,
	"Contact & News":   125,
	"Contact us":       126,
	"Country options are limited by your IP address and browser language.": 87,
	"Croatia":               29,
	"Currency":              139,
	"Current deletion date": 92,
	"Cyprus":                19,
	"Czech koruna":          54,
	"Czechia":               20,
	"Danish krone":          55,
	"Denmark":               22,
	"Digital Goods":         121,
	"Email":                 103,
	"Enter the quantity and press „Buy“.":                             71,
	"Error displaying website. Please try again later.":               9,
	"Error getting stock from database. Please try again later.":      8,
	"Error inserting purchase into database. Please try again later.": 11,
	"Error saving notify information. Please try again later.":        14,
	"Estonia":        23,
	"European Union": 84,
	"Finalized":      7,
	"Finland":        25,
	"France":         26,
	"Germany":        21,
	"Get notified when your payment arrives and your voucher codes are shown. The notification will not contain the order number or the link. Your contact information will be deleted afterwards.": 101,
	"Got an idea or found an error? Drop us a note!": 131,
	"Greece":          28,
	"Hungary":         30,
	"IBAN":            146,
	"Icelandic króna": 57,
	"If you are sending coins, please stick them down firmly. Otherwise they will be pressed out during transport.":                                                                                   141,
	"If you use TOR or a VPN: The payment options displayed depend on the country of your IP address. In addition, PayPal blocks some TOR exit nodes. In that case, try „New Circuit for this Site“.": 143,
	"Imprint":      113,
	"Ireland":      31,
	"Italy":        32,
	"Japanese yen": 58,
	"JavaScript is disabled in your browser. In order to receive updates on your order, please reload this page from time to time.": 93,
	"Latvia":      35,
	"Legal":       110,
	"Lithuania":   33,
	"Local Store": 120,
	"Luxembourg":  34,
	"Make a bank transfer to our German SEPA (Single Euro Payments Area) bank account. We check for new incoming payments manually every day. We will see your name and account number on our bank statement. If your bank account is outside the Single Euro Payments Area, please pay any fees yourself by selecting the „OUR“ fee option.": 144,
	"Malta":              37,
	"Message from store": 91,
	"Mon+Thu 2pm-6pm":    128,
	"Monero (XMR) or Bitcoin (BTC): Your voucher codes are shown as soon as your payment is confirmed on the blockchain.": 75,
	"Monero and Bitcoin":        116,
	"Monero or Bitcoin":         45,
	"Montenegro":                36,
	"Netherlands":               38,
	"New":                       4,
	"New Israeli shekel (NIS)":  59,
	"New Taiwan dollars":        66,
	"New Zealand dollars":       61,
	"Norwegian krone":           60,
	"Not in the European Union": 83,
	"Online printing":           124,
	"Online shop":               122,
	"Opening hours":             127,
	"Optional: Get notified by email or ntfy.sh when your payment arrives.": 78,
	"Optional: Get notified when your payment arrives":                      100,
	"Or scan the EPC QR code:":                                              151,
	"Order":                                                                 89,
	"Order Service":                                                         123,
	"Order with a few clicks. Pay with Monero, Bitcoin, cash in 20 currencies, or SEPA Bank transfer.": 69,
	"Our service thinks that you are a bot. If you are not, please contact us.":                        10,
	"Overall Sum": 108,
	"Pay the specified amount in one of the following currencies.": 136,
	"Pay using Monero or Bitcoin":                                  133,
	"Pay with Monero (XMR) or Bitcoin (BTC). The full amount must be paid with a single transaction to the given address within 60 minutes. If your payment arrives too late, we have to confirm it manually. If in doubt, please contact us.": 132,
	"Pay your order.": 73,
	"Pay your order. Unpaid orders are deleted after 30 days.": 97,
	"Payment":            99,
	"Payment processing": 5,
	"Please include a note with this order number":                                  135,
	"Please select some products.":                                                  80,
	"Please select your country of residence.":                                      86,
	"Please send banknotes only and round up if necessary. We do not accept coins.": 137,
	"Poland":         39,
	"Polish złoty":   62,
	"Portugal":       40,
	"Pound sterling": 56,
	"Privacy policy": 112,
	"Purpose":        150,
	"Read more":      70,
	"Romania":        41,
	"Romanian leu":   63,
	"SEPA (Single Euro Payments Area) bank transfer to our German bank account. We manually check for new payments every day.": 77,
	"SEPA bank transfer":              117,
	"Save":                            105,
	"See here for short-term changes": 130,
	"Select":                          102,
	"Send cash in an insured letter or package to our store address in Germany. After we take out the money, we shred the letter. Please check the cash shipment limits of your postal company (e. g. Deutsche Post „Einschreiben Wert“ up to 100 Euros within Germany, DHL Parcel up to 500 Euros). Send it to:": 134,
	"Serbian dinar":                  64,
	"Show prices and delivery dates": 109,
	"Slovakia":                       44,
	"Slovenia":                       43,
	"Spain":                          24,
	"Status":                         90,
	"Sweden":                         42,
	"Swedish krona":                  65,
	"Swiss francs":                   52,
	"Switzerland":                    18,
	"Terms and Conditions":           111,
	"There is no such purchase, or it has been deleted, or the URL is incorrect.": 12,
	"There is no such purchase, or it has been deleted.":                          13,
	"Tue+Wed+Fri+Sat 10am-2pm":                                                    129,
	"Underdelivered":                                                              6,
	"United Kingdom":                                                              27,
	"United States dollars":                                                       67,
	"Unpaid orders are deleted after 30 days.":                                    74,
	"We are waiting for your payment.":                                            0,
	"We have received your payment, but have gone out of stock meanwhile. You will receive the missing codes here as soon as possible. Sorry for the inconvenience.": 2,
	"We only send the order number to PayPal. Your ordered items and delivery or pickup details will not be sent to PayPal.":                                         142,
	"What's next?": 94,
	"Where do you live? (We have to ask that for tax reasons. It does not affect the price or the goods.)": 82,
	"Why?": 119,
	"Write down your codes. We will delete them 30 days after delivery.":                                       79,
	"You will receive the missing codes here as soon as they are in stock again. Sorry for the inconvenience.": 107,
	"Your Order":                      106,
	"Your codes have been delivered.": 3,
	"in stock":                        81,
	"please select":                   85,
}

var de_DEIndex = []uint32{ // 153 elements
	// Entry 0 - 1F
	0x00000000, 0x0000002b, 0x000000a1, 0x00000155,
	0x00000176, 0x0000017a, 0x00000193, 0x000001a2,
	0x000001b0, 0x0000020b, 0x00000252, 0x000002ab,
	0x00000309, 0x00000368, 0x000003a7, 0x00000408,
	0x00000414, 0x0000041c, 0x00000426, 0x0000042e,
	0x00000435, 0x00000440, 0x0000044c, 0x00000456,
	0x0000045e, 0x00000466, 0x0000046f, 0x0000047a,
	0x00000492, 0x0000049f, 0x000004a8, 0x000004af,
	// Entry 20 - 3F
	0x000004b6, 0x000004be, 0x000004c6, 0x000004d0,
	0x000004d9, 0x000004e4, 0x000004ea, 0x000004f6,
	0x000004fc, 0x00000505, 0x0000050f, 0x00000518,
	0x00000522, 0x0000052b, 0x0000053f, 0x00000558,
	0x00000560, 0x00000586, 0x0000059a, 0x000005aa,
	0x000005bc, 0x000005ce, 0x000005e3, 0x000005f7,
	0x00000608, 0x00000618, 0x0000062c, 0x0000063b,
	0x0000065a, 0x0000066d, 0x0000067f, 0x00000690,
	// Entry 40 - 5F
	0x000006a0, 0x000006b0, 0x000006c3, 0x000006d1,
	0x000006db, 0x00000784, 0x000007f4, 0x00000800,
	0x0000083b, 0x00000896, 0x000008b0, 0x000008e8,
	0x00000967, 0x000009f2, 0x00000a5f, 0x00000aba,
	0x00000b08, 0x00000b36, 0x00000b40, 0x00000bcf,
	0x00000bf2, 0x00000c05, 0x00000c16, 0x00000c43,
	0x00000c8f, 0x00000c96, 0x00000ca1, 0x00000ca8,
	0x00000cbb, 0x00000cd3, 0x00000d45, 0x00000d59,
	// Entry 60 - 7F
	0x00000dd3, 0x00000dea, 0x00000e3c, 0x00000f27,
	0x00000f2f, 0x00000f71, 0x0000104e, 0x00001059,
	0x00001060, 0x00001069, 0x00001073, 0x00001084,
	0x000010f1, 0x000010fd, 0x0000111d, 0x00001129,
	0x0000112d, 0x00001139, 0x00001143, 0x00001156,
	0x00001178, 0x0000118b, 0x000011a1, 0x000011bc,
	0x000011c3, 0x000011d2, 0x000011e2, 0x000011ed,
	0x000011fc, 0x0000120c, 0x0000121b, 0x00001223,
	// Entry 80 - 9F
	0x00001233, 0x00001243, 0x00001259, 0x00001281,
	0x000012a4, 0x000013d1, 0x000013f7, 0x0000153a,
	0x0000156c, 0x000015ac, 0x00001601, 0x00001608,
	0x00001611, 0x00001616, 0x0000167b, 0x00001714,
	0x0000180e, 0x00001981, 0x0000198e, 0x00001993,
	0x000019a6, 0x000019ba, 0x000019c3, 0x000019d6,
	0x000019f3,
} // Size: 636 bytes

const de_DEData string = "" + // Size: 6643 bytes
	"\x02Wir warten auf den Eingang deiner Zahlung.\x02Eine Zahlung wurde ang" +
	"ekündigt, aber wir warten noch auf die erforderliche Anzahl Bestätigunge" +
	"n auf der Blockchain.\x02Wir haben deine Zahlung erhalten, aber unser Vo" +
	"rrat wurde zwischenzeitlich ausverkauft. Die fehlenden Codes erhälst du " +
	"möglichst bald. Wir bitten die Umstände zu entschuldigen.\x02Deine Codes" +
	" wurden ausgeliefert.\x02Neu\x02Zahlung wird verarbeitet\x02Unterbeliefe" +
	"rt\x02Abgeschlossen\x02Fehler beim Abrufen des Bestands aus der Datenban" +
	"k. Bitte versuche es später noch einmal.\x02Fehler beim Anzeigen der Sei" +
	"te. Bitte versuche es später noch einmal.\x02Unser Server denkt, dass du" +
	" ein Bot bist. Falls du kein Bot bist, kontaktiere uns bitte.\x02Fehler " +
	"beim Einfügen der Bestellung in die Datenbank. Bitte versuche es später " +
	"noch einmal.\x02Diese Bestellung existiert nicht oder wurde bereits gelö" +
	"scht, oder die Webadresse ist falsch.\x02Diese Bestellung existiert nich" +
	"t oder wurde bereits gelöscht.\x02Fehler beim Speichern der Benachrichti" +
	"gungseinstellungen. Bitte versuche es später noch einmal.\x02Österreich" +
	"\x02Belgien\x02Bulgarien\x02Schweiz\x02Zypern\x02Tschechien\x02Deutschla" +
	"nd\x02Dänemark\x02Estland\x02Spanien\x02Finnland\x02Frankreich\x02Verein" +
	"igtes Königreich\x02Griechenland\x02Kroatien\x02Ungarn\x02Irland\x02Ital" +
	"ien\x02Litauen\x02Luxemburg\x02Lettland\x02Montenegro\x02Malta\x02Nieder" +
	"lande\x02Polen\x02Portugal\x02Rumänien\x02Schweden\x02Slowenien\x02Slowa" +
	"kei\x02Monero oder Bitcoin\x02Bargeld in Fremdwährung\x02Bargeld\x02Bank" +
	"überweisung auf unser SEPA-Konto\x02Australische Dollar\x02Bulgarische " +
	"Lew\x02Kanadische Dollar\x02Schweizer Franken\x02Chinesische Renminbi" +
	"\x02Tschechische Kronen\x02Dänische Kronen\x02Britische Pfund\x02Isländi" +
	"sche Kronen\x02Japanische Yen\x02Neue israelische Schekel (NIS)\x02Norwe" +
	"gische Kronen\x02Neuseeland-Dollar\x02Polnische Złoty\x02Rumänische Leu" +
	"\x02Serbische Dinar\x02Schwedische Kronen\x02Taiwan-Dollar\x02US-Dollar" +
	"\x02Hier kannst du Gutscheine für Privatsphäre-freundliche Dienste kaufe" +
	"n und anonym mit Monero, Bitcoin oder Bargeld bezahlen. SEPA-Banküberwei" +
	"sung ist auch verfügbar.\x02Bestelle mit wenigen Klicks. Bezahle mit Mon" +
	"ero, Bitcoin, Bargeld in 20 Währungen, oder SEPA-Banküberweisung.\x02Wei" +
	"terlesen\x02Wähle die gewünschte Anzahl aus und klicke „Kaufen“.\x02Spei" +
	"chere deine Bestellung als Lesezeichen. Du brauchst sie, um auf die Code" +
	"s zuzugreifen.\x02Bezahle deine Bestellung.\x02Unbezahlte Bestellungen w" +
	"erden nach 30 Tagen gelöscht.\x02Monero (XMR) oder Bitcoin (BTC): Deine " +
	"Gutscheincodes werden angezeigt, sobald deine Zahlung in der Blockchain " +
	"bestätigt ist.\x02Bargeld: Schicke Bargeld (wir akzeptieren 20 Währungen" +
	") an unsere Adresse in Deutschland. Wir schreddern den Brief nach dem Fr" +
	"eischalten.\x02SEPA-Überweisung auf unser deutsches Bankkonto. Wir prüfe" +
	"n es täglich manuell auf neue Zahlungseingänge.\x02Optional: Lass dich p" +
	"er E-Mail oder ntfy.sh benachrichtigen, wenn deine Zahlung eintrifft." +
	"\x02Notiere dir die Codes. Wir werden sie 30 Tage nach der Auslieferung " +
	"löschen.\x02Bitte wähle eines oder mehrere Produkte aus.\x02vorrätig\x02" +
	"In welchem Land bist du ansässig? (Das müssen wir aus steuerlichen Gründ" +
	"en fragen. Es hat keinen Einfluss auf den Preis oder die Leistung.)\x02A" +
	"ußerhalb der Europäischen Union\x02Europäische Union\x02bitte auswählen" +
	"\x02Bitte wähle das Land aus, in dem du wohnst.\x02Die Länderoptionen hä" +
	"ngen von deiner IP-Adresse und Spracheinstellung ab.\x02Kaufen\x02Bestel" +
	"lung\x02Status\x02Nachricht vom Shop\x02Derzeitiges Löschdatum\x02Du has" +
	"t JavaScript deaktiviert. Um über Neuigkeiten informiert zu werden, lade" +
	" die Seite bitte gelegentlich neu.\x02Wie geht es weiter?\x02Setze diese" +
	" Seite als Lesezeichen oder speichere ihre Adresse anderweitig. Du brauc" +
	"hst sie, um auf die Codes zuzugreifen.\x02Anklicken zum Kopieren\x02Beza" +
	"hle deine Bestellung. Unbezahlte Bestellungen werden nach 30 Tagen gelös" +
	"cht.\x02Sobald deine Zahlung bei uns eintrifft, werden dir deine Gutsche" +
	"incodes angezeigt. In seltenen Fällen kann es passieren, dass das Produk" +
	"t zwischenzeitlich ausverkauft ist. Dann werden dir die Codes angezeigt," +
	" sobald Nachschub da ist.\x02Zahlung\x02Optional: Lass dich benachrichti" +
	"gen, wenn deine Zahlung eintrifft\x02Lass dich benachrichtigen, wenn dei" +
	"ne Zahlung eingegangen ist und die Voucher-Codes angezeigt werden. Die B" +
	"enachrichtigung wird weder die Bestellnummer noch den Link enthalten. De" +
	"ine Kontaktdaten werden danach gelöscht.\x02Wähle aus\x02E-Mail\x02Addre" +
	"sse\x02Speichern\x02Deine Bestellung\x02Die fehlenden Codes erhälst du, " +
	"sobald Nachschub eintroffen ist. Wir bitten die Umstände zu entschuldige" +
	"n.\x02Gesamtsumme\x02Preise und Lieferdatum anzeigen\x02Rechtliches\x02A" +
	"GB\x02Datenschutz\x02Impressum\x02Widerrufsbelehrung\x02Bargeld per Post" +
	" in 20 Währungen\x02Monero und Bitcoin\x02SEPA-Banküberweisung\x02Alle A" +
	"ngebote und Projekte\x02Warum?\x02Ladengeschäft\x02Digitale Güter\x02Onl" +
	"ineshop\x02Bestellservice\x02Onlinedruckerei\x02Kontakt & News\x02Kontak" +
	"t\x02Öffnungszeiten\x02Mo+Do 14-18 Uhr\x02Di+Mi+Fr+Sa 10-14 Uhr\x02Sieh " +
	"hier für kurzfristige Änderungen\x02Fehler oder Hinweise? Schreib uns!" +
	"\x02Bezahle den angegebenen Betrag in Monero (XMR) oder Bitcoin (BTC). D" +
	"er Betrag muss innerhalb von 60 Minuten vollständig und als einzelne Tra" +
	"nsaktion auf der angegebenen Adresse eingehen. Falls deine Zahlung versp" +
	"ätet eintrifft, müssen wir sie manuell bestätigen. Im Zweifel kontaktie" +
	"re uns bitte.\x02Zur Bezahlung mit Monero oder Bitcoin\x02Sende uns Barg" +
	"eld in einem versichertem Brief oder Paket. Nachdem wir das Geld entnomm" +
	"en haben, schreddern wir den Brief. Bitte beachte die Höchstgrenzen dein" +
	"es Postunternehmens für den Bargeldversand (z. B. Deutsche Post „Einschr" +
	"eiben Wert“ bis 100 Euro innerhalb Deutschlands, DHL Paket bis 500 Euro)" +
	". Sende es an:\x02Bitte lege einen Zettel mit der Bestellnummer bei\x02Z" +
	"ahle den angegebenen Betrag in einer der folgenden Währungen.\x02Bitte s" +
	"ende nur Banknoten und runde gegebenenfalls auf. Wir nehmen keine Münzen" +
	" an.\x02Betrag\x02Währung\x02%.2f\x02Falls du Münzen sendest, klebe sie " +
	"bitte gut fest. Sonst werden sie beim Transport herausgedrückt.\x02Wir ü" +
	"bermitteln nur die Bestellnummer an PayPal. Deine bestellten Artikel sow" +
	"ie die Details zu Lieferung oder Abholung werden nicht an PayPal gesende" +
	"t.\x02Falls du TOR oder einen VPN benutzt: Die angezeigten Bezahlmöglich" +
	"keiten sind von der Länderzuordnung deiner IP-Adresse abhängig. Darüber " +
	"hinaus blockiert PayPal manche TOR Exit Nodes. In dem Fall versuche es m" +
	"it „New Circuit for this Site“.\x02Überweise das Geld auf unser deutsche" +
	"s SEPA-Bankkonto. Wir prüfen es täglich manuell auf neue Zahlungseingäng" +
	"e. Wir werden deinen Namen und deine Kontonummer auf unserem Kontoauszug" +
	" sehen. Falls dein Konto außerhalb des einheitlichen Euro-Zahlungsverkeh" +
	"rsraums (SEPA) liegt, zahle eventuelle Gebühren bitte selbst, indem du d" +
	"ie Gebührenregelung „OUR“ wählst.\x02Kontoinhaber\x02IBAN\x02BIC (falls " +
	"nötig)\x02Bank (falls nötig)\x02%.2f €\x02Überweisungszweck\x02Oder scan" +
	"ne den EPC-QR-Code:"

var en_USIndex = []uint32{ // 153 elements
	// Entry 0 - 1F
	0x00000000, 0x00000021, 0x0000008e, 0x0000012d,
	0x0000014d, 0x00000151, 0x00000164, 0x00000173,
	0x0000017d, 0x000001b8, 0x000001ea, 0x00000234,
	0x00000274, 0x000002c0, 0x000002f3, 0x0000032c,
	0x00000334, 0x0000033c, 0x00000345, 0x00000351,
	0x00000358, 0x00000360, 0x00000368, 0x00000370,
	0x00000378, 0x0000037e, 0x00000386, 0x0000038d,
	0x0000039c, 0x000003a3, 0x000003ab, 0x000003b3,
	// Entry 20 - 3F
	0x000003bb, 0x000003c1, 0x000003cb, 0x000003d6,
	0x000003dd, 0x000003e8, 0x000003ee, 0x000003fa,
	0x00000401, 0x0000040a, 0x00000412, 0x00000419,
	0x00000422, 0x0000042b, 0x0000043d, 0x00000456,
	0x0000045b, 0x0000047d, 0x00000490, 0x0000049e,
	0x000004af, 0x000004bc, 0x000004cd, 0x000004da,
	0x000004e7, 0x000004f6, 0x00000507, 0x00000514,
	0x0000052d, 0x0000053d, 0x00000551, 0x0000055f,
	// Entry 40 - 5F
	0x0000056c, 0x0000057a, 0x00000588, 0x0000059b,
	0x000005b1, 0x0000064f, 0x000006b0, 0x000006ba,
	0x000006e2, 0x0000071e, 0x0000072e, 0x00000757,
	0x000007cb, 0x00000835, 0x000008ae, 0x000008f4,
	0x00000937, 0x00000954, 0x0000095d, 0x000009c2,
	0x000009dc, 0x000009eb, 0x000009f9, 0x00000a22,
	0x00000a67, 0x00000a6b, 0x00000a71, 0x00000a78,
	0x00000a8b, 0x00000aa1, 0x00000b1f, 0x00000b2c,
	// Entry 60 - 7F
	0x00000b8a, 0x00000b98, 0x00000bd1, 0x00000c95,
	0x00000c9d, 0x00000cce, 0x00000d8c, 0x00000d93,
	0x00000d99, 0x00000da1, 0x00000da6, 0x00000db1,
	0x00000e1a, 0x00000e26, 0x00000e45, 0x00000e4b,
	0x00000e60, 0x00000e6f, 0x00000e77, 0x00000e8b,
	0x00000ea9, 0x00000ebc, 0x00000ecf, 0x00000ee9,
	0x00000eee, 0x00000efa, 0x00000f08, 0x00000f14,
	0x00000f22, 0x00000f32, 0x00000f41, 0x00000f4c,
	// Entry 80 - 9F
	0x00000f5a, 0x00000f6a, 0x00000f83, 0x00000fa3,
	0x00000fd2, 0x000010bb, 0x000010d7, 0x00001207,
	0x00001234, 0x00001271, 0x000012bf, 0x000012c6,
	0x000012cf, 0x000012d4, 0x00001342, 0x000013b9,
	0x0000147d, 0x000015c9, 0x000015d8, 0x000015dd,
	0x000015ef, 0x00001607, 0x00001610, 0x00001618,
	0x00001631,
} // Size: 636 bytes

const en_USData string = "" + // Size: 5681 bytes
	"\x02We are waiting for your payment.\x02A payment is on the way, but we'" +
	"re still waiting for the required amount of confirmations on the blockch" +
	"ain.\x02We have received your payment, but have gone out of stock meanwh" +
	"ile. You will receive the missing codes here as soon as possible. Sorry " +
	"for the inconvenience.\x02Your codes have been delivered.\x02New\x02Paym" +
	"ent processing\x02Underdelivered\x02Finalized\x02Error getting stock fro" +
	"m database. Please try again later.\x02Error displaying website. Please " +
	"try again later.\x02Our service thinks that you are a bot. If you are no" +
	"t, please contact us.\x02Error inserting purchase into database. Please " +
	"try again later.\x02There is no such purchase, or it has been deleted, o" +
	"r the URL is incorrect.\x02There is no such purchase, or it has been del" +
	"eted.\x02Error saving notify information. Please try again later.\x02Aus" +
	"tria\x02Belgium\x02Bulgaria\x02Switzerland\x02Cyprus\x02Czechia\x02Germa" +
	"ny\x02Denmark\x02Estonia\x02Spain\x02Finland\x02France\x02United Kingdom" +
	"\x02Greece\x02Croatia\x02Hungary\x02Ireland\x02Italy\x02Lithuania\x02Lux" +
	"embourg\x02Latvia\x02Montenegro\x02Malta\x02Netherlands\x02Poland\x02Por" +
	"tugal\x02Romania\x02Sweden\x02Slovenia\x02Slovakia\x02Monero or Bitcoin" +
	"\x02Cash in Foreign Currency\x02Cash\x02Bank Transfer to our SEPA Accoun" +
	"t\x02Australian dollars\x02Bulgarian lev\x02Canadian dollars\x02Swiss fr" +
	"ancs\x02Chinese renminbi\x02Czech koruna\x02Danish krone\x02Pound sterli" +
	"ng\x02Icelandic króna\x02Japanese yen\x02New Israeli shekel (NIS)\x02Nor" +
	"wegian krone\x02New Zealand dollars\x02Polish złoty\x02Romanian leu\x02S" +
	"erbian dinar\x02Swedish krona\x02New Taiwan dollars\x02United States dol" +
	"lars\x02Buy coupons, voucher codes and gift cards for privacy services a" +
	"nd pay anonymously with Monero, Bitcoin or cash letter. SEPA Bank transf" +
	"er is also available.\x02Order with a few clicks. Pay with Monero, Bitco" +
	"in, cash in 20 currencies, or SEPA Bank transfer.\x02Read more\x02Enter " +
	"the quantity and press „Buy“.\x02Bookmark your order. You will need it t" +
	"o access your goods.\x02Pay your order.\x02Unpaid orders are deleted aft" +
	"er 30 days.\x02Monero (XMR) or Bitcoin (BTC): Your voucher codes are sho" +
	"wn as soon as your payment is confirmed on the blockchain.\x02Cash: Send" +
	" cash (we accept 20 currencies) to our office in Germany. We shred the l" +
	"etter after processing.\x02SEPA (Single Euro Payments Area) bank transfe" +
	"r to our German bank account. We manually check for new payments every d" +
	"ay.\x02Optional: Get notified by email or ntfy.sh when your payment arri" +
	"ves.\x02Write down your codes. We will delete them 30 days after deliver" +
	"y.\x02Please select some products.\x02in stock\x02Where do you live? (We" +
	" have to ask that for tax reasons. It does not affect the price or the g" +
	"oods.)\x02Not in the European Union\x02European Union\x02please select" +
	"\x02Please select your country of residence.\x02Country options are limi" +
	"ted by your IP address and browser language.\x02Buy\x02Order\x02Status" +
	"\x02Message from store\x02Current deletion date\x02JavaScript is disable" +
	"d in your browser. In order to receive updates on your order, please rel" +
	"oad this page from time to time.\x02What's next?\x02Bookmark this page o" +
	"r save its address in another way. You will need it to access your goods" +
	".\x02Click to copy\x02Pay your order. Unpaid orders are deleted after 30" +
	" days.\x02As soon as your payment arrives, your voucher codes are shown." +
	" In the unlikely case that your goods have become sold out in the meanti" +
	"me, your codes will appear as soon as they are back in stock.\x02Payment" +
	"\x02Optional: Get notified when your payment arrives\x02Get notified whe" +
	"n your payment arrives and your voucher codes are shown. The notificatio" +
	"n will not contain the order number or the link. Your contact informatio" +
	"n will be deleted afterwards.\x02Select\x02Email\x02Address\x02Save\x02Y" +
	"our Order\x02You will receive the missing codes here as soon as they are" +
	" in stock again. Sorry for the inconvenience.\x02Overall Sum\x02Show pri" +
	"ces and delivery dates\x02Legal\x02Terms and Conditions\x02Privacy polic" +
	"y\x02Imprint\x02Cancellation Policy\x02Cash by mail in 20 currencies\x02" +
	"Monero and Bitcoin\x02SEPA bank transfer\x02All Services and Projects" +
	"\x02Why?\x02Local Store\x02Digital Goods\x02Online shop\x02Order Service" +
	"\x02Online printing\x02Contact & News\x02Contact us\x02Opening hours\x02" +
	"Mon+Thu 2pm-6pm\x02Tue+Wed+Fri+Sat 10am-2pm\x02See here for short-term c" +
	"hanges\x02Got an idea or found an error? Drop us a note!\x02Pay with Mon" +
	"ero (XMR) or Bitcoin (BTC). The full amount must be paid with a single t" +
	"ransaction to the given address within 60 minutes. If your payment arriv" +
	"es too late, we have to confirm it manually. If in doubt, please contact" +
	" us.\x02Pay using Monero or Bitcoin\x02Send cash in an insured letter or" +
	" package to our store address in Germany. After we take out the money, w" +
	"e shred the letter. Please check the cash shipment limits of your postal" +
	" company (e. g. Deutsche Post „Einschreiben Wert“ up to 100 Euros within" +
	" Germany, DHL Parcel up to 500 Euros). Send it to:\x02Please include a n" +
	"ote with this order number\x02Pay the specified amount in one of the fol" +
	"lowing currencies.\x02Please send banknotes only and round up if necessa" +
	"ry. We do not accept coins.\x02Amount\x02Currency\x02%.2f\x02If you are " +
	"sending coins, please stick them down firmly. Otherwise they will be pre" +
	"ssed out during transport.\x02We only send the order number to PayPal. Y" +
	"our ordered items and delivery or pickup details will not be sent to Pay" +
	"Pal.\x02If you use TOR or a VPN: The payment options displayed depend on" +
	" the country of your IP address. In addition, PayPal blocks some TOR exi" +
	"t nodes. In that case, try „New Circuit for this Site“.\x02Make a bank t" +
	"ransfer to our German SEPA (Single Euro Payments Area) bank account. We " +
	"check for new incoming payments manually every day. We will see your nam" +
	"e and account number on our bank statement. If your bank account is outs" +
	"ide the Single Euro Payments Area, please pay any fees yourself by selec" +
	"ting the „OUR“ fee option.\x02Account holder\x02IBAN\x02BIC (if required" +
	")\x02Bank name (if required)\x02%.2f EUR\x02Purpose\x02Or scan the EPC Q" +
	"R code:"

	// Total table size 13596 bytes (13KiB); checksum: 443995E0
