// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package digitalgoods

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%.2f":     146,
	"%.2f EUR": 155,
	"A payment is on the way, but we're still waiting for the required amount of confirmations on the blockchain.": 1,
	"Account holder":            151,
	"Address":                   103,
	"All Services and Projects": 124,
	"Amount":                    144,
	"As soon as your payment arrives, your voucher codes are shown. In the unlikely case that your goods have become sold out in the meantime, your codes will appear as soon as they are back in stock.": 97,
	"Australian dollars":                49,
	"Austria":                           15,
	"BIC (if required)":                 153,
	"Bank Transfer to our SEPA Account": 48,
	"Bank name (if required)":           154,
	"Belgium":                           16,
	"Bookmark this page or save its address in another way. You will need it to access your goods.": 94,
	"Bookmark your order. You will need it to access your goods.":                                   72,
	"Bulgaria":      17,
	"Bulgarian lev": 50,
	"Buy":           88,
	"Buy coupons, voucher codes and gift cards for privacy services and pay anonymously with Monero, Bitcoin or cash letter. SEPA Bank transfer is also available.": 68,
	"Canadian dollars":              51,
	"Cancellation Policy":           120,
	"Cash":                          47,
	"Cash by mail in 20 currencies": 121,
	"Cash in Foreign Currency":      46,
	"Cash: Send cash (we accept 20 currencies) to our office in Germany. We shred the letter after processing.": 76,
	"Chinese renminbi": 53,
	"Click to copy":    95,
	"Code":             113,
	"Contact & News":   131,
	"Contact us":       132,
	"Country options are limited by your IP address and browser language.": 87,
	"Croatia":               29,
	"Currency":              145,
	"Current deletion date": 91,
	"Cyprus":                19,
	"Czech koruna":          54,
	"Czechia":               20,
	"Danish krone":          55,
	"Delivery Date":         112,
	"Denmark":               22,
	"Digital Goods":         127,
	"Email":                 102,
	"Enter the quantity and press „Buy“.":                             71,
	"Error displaying website. Please try again later.":               9,
	"Error getting stock from database. Please try again later.":      8,
	"Error inserting purchase into database. Please try again later.": 11,
	"Error saving notify information. Please try again later.":        14,
	"Estonia":        23,
	"European Union": 84,
	"Finalized":      7,
	"Finland":        25,
	"France":         26,
	"Germany":        21,
	"Get notified when your payment arrives and your voucher codes are shown. The notification will not contain the order number or the link. Your contact information will be deleted afterwards.": 100,
	"Got an idea or found an error? Drop us a note!": 137,
	"Greece":          28,
	"Hungary":         30,
	"IBAN":            152,
	"Icelandic króna": 57,
	"If you are sending coins, please stick them down firmly. Otherwise they will be pressed out during transport.":                                                                                   147,
	"If you use TOR or a VPN: The payment options displayed depend on the country of your IP address. In addition, PayPal blocks some TOR exit nodes. In that case, try „New Circuit for this Site“.": 149,
	"Imprint":      119,
	"Ireland":      31,
	"Italy":        32,
	"Item Price":   108,
	"Japanese yen": 58,
	"JavaScript is disabled in your browser. In order to receive updates on your order, please reload this page from time to time.": 92,
	"Latvia":      35,
	"Legal":       116,
	"Lithuania":   33,
	"Local Store": 126,
	"Luxembourg":  34,
	"Make a bank transfer to our German SEPA (Single Euro Payments Area) bank account. We check for new incoming payments manually every day. We will see your name and account number on our bank statement. If your bank account is outside the Single Euro Payments Area, please pay any fees yourself by selecting the „OUR“ fee option.": 150,
	"Malta":           37,
	"Mon+Thu 2pm-6pm": 134,
	"Monero (XMR) or Bitcoin (BTC): Your voucher codes are shown as soon as your payment is confirmed on the blockchain.": 75,
	"Monero and Bitcoin":        122,
	"Monero or Bitcoin":         45,
	"Montenegro":                36,
	"Netherlands":               38,
	"New":                       4,
	"New Israeli shekel (NIS)":  59,
	"New Taiwan dollars":        66,
	"New Zealand dollars":       61,
	"Norwegian krone":           60,
	"Not in the European Union": 83,
	"Online printing":           130,
	"Online shop":               128,
	"Opening hours":             133,
	"Optional: Get notified by email or ntfy.sh when your payment arrives.": 78,
	"Optional: Get notified when your payment arrives":                      99,
	"Or scan the EPC QR code:":                                              157,
	"Order":                                                                 89,
	"Order Service":                                                         129,
	"Order with a few clicks. Pay with Monero, Bitcoin, cash in 20 currencies, or SEPA Bank transfer.": 69,
	"Our service thinks that you are a bot. If you are not, please contact us.":                        10,
	"Overall Sum": 110,
	"Pay the specified amount in one of the following currencies.": 142,
	"Pay using Monero or Bitcoin":                                  139,
	"Pay with Monero (XMR) or Bitcoin (BTC). The full amount must be paid with a single transaction to the given address within 60 minutes. If your payment arrives too late, we have to confirm it manually. If in doubt, please contact us.": 138,
	"Pay your order.": 73,
	"Pay your order. Unpaid orders are deleted after 30 days.": 96,
	"Payment":            98,
	"Payment processing": 5,
	"Please include a note with this order number":                                  141,
	"Please select some products.":                                                  80,
	"Please select your country of residence.":                                      86,
	"Please send banknotes only and round up if necessary. We do not accept coins.": 143,
	"Poland":         39,
	"Polish złoty":   62,
	"Portugal":       40,
	"Pound sterling": 56,
	"Privacy policy": 118,
	"Product":        106,
	"Purpose":        156,
	"Quantity":       107,
	"Read more":      70,
	"Romania":        41,
	"Romanian leu":   63,
	"SEPA (Single Euro Payments Area) bank transfer to our German bank account. We manually check for new payments every day.": 77,
	"SEPA bank transfer":              123,
	"Save":                            104,
	"See here for short-term changes": 136,
	"Select":                          101,
	"Send cash in an insured letter or package to our store address in Germany. After we take out the money, we shred the letter. Please check the cash shipment limits of your postal company (e. g. Deutsche Post „Einschreiben Wert“ up to 100 Euros within Germany, DHL Parcel up to 500 Euros). Send it to:": 140,
	"Serbian dinar":        64,
	"Slovakia":             44,
	"Slovenia":             43,
	"Spain":                24,
	"Status":               90,
	"Sum":                  109,
	"Sweden":               42,
	"Swedish krona":        65,
	"Swiss francs":         52,
	"Switzerland":          18,
	"Terms and Conditions": 117,
	"There is no such purchase, or it has been deleted, or the URL is incorrect.": 12,
	"There is no such purchase, or it has been deleted.":                          13,
	"Tue+Wed+Fri+Sat 10am-2pm":                                                    135,
	"Underdelivered":                                                              6,
	"United Kingdom":                                                              27,
	"United States dollars":                                                       67,
	"Unpaid orders are deleted after 30 days.":                                    74,
	"We are waiting for your payment.":                                            0,
	"We have received your payment, but have gone out of stock meanwhile. You will receive the missing codes here as soon as possible. Sorry for the inconvenience.": 2,
	"We only send the order number to PayPal. Your ordered items and delivery or pickup details will not be sent to PayPal.":                                         148,
	"What's next?": 93,
	"Where do you live? (We have to ask that for tax reasons. It does not affect the price or the goods.)": 82,
	"Why?": 125,
	"Write down your codes. We will delete them 30 days after delivery.":                                       79,
	"You will receive the missing codes here as soon as they are in stock again. Sorry for the inconvenience.": 114,
	"You will receive your codes as soon as you payment has arrived.":                                          115,
	"Your Goods":                      111,
	"Your Order":                      105,
	"Your codes have been delivered.": 3,
	"in stock":                        81,
	"please select":                   85,
}

var de_DEIndex = []uint32{ // 159 elements
	// Entry 0 - 1F
	0x00000000, 0x0000002b, 0x000000a1, 0x00000155,
	0x00000176, 0x0000017a, 0x00000193, 0x000001a2,
	0x000001b0, 0x0000020b, 0x00000252, 0x000002ab,
	0x00000309, 0x00000368, 0x000003a7, 0x00000408,
	0x00000414, 0x0000041c, 0x00000426, 0x0000042e,
	0x00000435, 0x00000440, 0x0000044c, 0x00000456,
	0x0000045e, 0x00000466, 0x0000046f, 0x0000047a,
	0x00000492, 0x0000049f, 0x000004a8, 0x000004af,
	// Entry 20 - 3F
	0x000004b6, 0x000004be, 0x000004c6, 0x000004d0,
	0x000004d9, 0x000004e4, 0x000004ea, 0x000004f6,
	0x000004fc, 0x00000505, 0x0000050f, 0x00000518,
	0x00000522, 0x0000052b, 0x0000053f, 0x00000558,
	0x00000560, 0x00000586, 0x0000059a, 0x000005aa,
	0x000005bc, 0x000005ce, 0x000005e3, 0x000005f7,
	0x00000608, 0x00000618, 0x0000062c, 0x0000063b,
	0x0000065a, 0x0000066d, 0x0000067f, 0x00000690,
	// Entry 40 - 5F
	0x000006a0, 0x000006b0, 0x000006c3, 0x000006d1,
	0x000006db, 0x00000784, 0x000007f4, 0x00000800,
	0x0000083b, 0x00000896, 0x000008b0, 0x000008e8,
	0x00000967, 0x000009f2, 0x00000a5f, 0x00000aba,
	0x00000b08, 0x00000b36, 0x00000b40, 0x00000bcf,
	0x00000bf2, 0x00000c05, 0x00000c16, 0x00000c43,
	0x00000c8f, 0x00000c96, 0x00000ca1, 0x00000ca8,
	0x00000cc0, 0x00000d32, 0x00000d46, 0x00000dc0,
	// Entry 60 - 7F
	0x00000dd7, 0x00000e29, 0x00000f14, 0x00000f1c,
	0x00000f5e, 0x0000103b, 0x00001046, 0x0000104d,
	0x00001056, 0x00001060, 0x00001071, 0x00001079,
	0x00001080, 0x0000108c, 0x00001092, 0x0000109e,
	0x000010a9, 0x000010b5, 0x000010ba, 0x00001127,
	0x0000116c, 0x00001178, 0x0000117c, 0x00001188,
	0x00001192, 0x000011a5, 0x000011c7, 0x000011da,
	0x000011f0, 0x0000120b, 0x00001212, 0x00001221,
	// Entry 80 - 9F
	0x00001231, 0x0000123c, 0x0000124b, 0x0000125b,
	0x0000126a, 0x00001272, 0x00001282, 0x00001292,
	0x000012a8, 0x000012d0, 0x000012f3, 0x00001420,
	0x00001446, 0x00001589, 0x000015bb, 0x000015fb,
	0x00001650, 0x00001657, 0x00001660, 0x00001665,
	0x000016ca, 0x00001763, 0x0000185d, 0x000019d0,
	0x000019dd, 0x000019e2, 0x000019f5, 0x00001a09,
	0x00001a12, 0x00001a25, 0x00001a42,
} // Size: 660 bytes

const de_DEData string = "" + // Size: 6722 bytes
	"\x02Wir warten auf den Eingang deiner Zahlung.\x02Eine Zahlung wurde ang" +
	"ekündigt, aber wir warten noch auf die erforderliche Anzahl Bestätigunge" +
	"n auf der Blockchain.\x02Wir haben deine Zahlung erhalten, aber unser Vo" +
	"rrat wurde zwischenzeitlich ausverkauft. Die fehlenden Codes erhälst du " +
	"möglichst bald. Wir bitten die Umstände zu entschuldigen.\x02Deine Codes" +
	" wurden ausgeliefert.\x02Neu\x02Zahlung wird verarbeitet\x02Unterbeliefe" +
	"rt\x02Abgeschlossen\x02Fehler beim Abrufen des Bestands aus der Datenban" +
	"k. Bitte versuche es später noch einmal.\x02Fehler beim Anzeigen der Sei" +
	"te. Bitte versuche es später noch einmal.\x02Unser Server denkt, dass du" +
	" ein Bot bist. Falls du kein Bot bist, kontaktiere uns bitte.\x02Fehler " +
	"beim Einfügen der Bestellung in die Datenbank. Bitte versuche es später " +
	"noch einmal.\x02Diese Bestellung existiert nicht oder wurde bereits gelö" +
	"scht, oder die Webadresse ist falsch.\x02Diese Bestellung existiert nich" +
	"t oder wurde bereits gelöscht.\x02Fehler beim Speichern der Benachrichti" +
	"gungseinstellungen. Bitte versuche es später noch einmal.\x02Österreich" +
	"\x02Belgien\x02Bulgarien\x02Schweiz\x02Zypern\x02Tschechien\x02Deutschla" +
	"nd\x02Dänemark\x02Estland\x02Spanien\x02Finnland\x02Frankreich\x02Verein" +
	"igtes Königreich\x02Griechenland\x02Kroatien\x02Ungarn\x02Irland\x02Ital" +
	"ien\x02Litauen\x02Luxemburg\x02Lettland\x02Montenegro\x02Malta\x02Nieder" +
	"lande\x02Polen\x02Portugal\x02Rumänien\x02Schweden\x02Slowenien\x02Slowa" +
	"kei\x02Monero oder Bitcoin\x02Bargeld in Fremdwährung\x02Bargeld\x02Bank" +
	"überweisung auf unser SEPA-Konto\x02Australische Dollar\x02Bulgarische " +
	"Lew\x02Kanadische Dollar\x02Schweizer Franken\x02Chinesische Renminbi" +
	"\x02Tschechische Kronen\x02Dänische Kronen\x02Britische Pfund\x02Isländi" +
	"sche Kronen\x02Japanische Yen\x02Neue israelische Schekel (NIS)\x02Norwe" +
	"gische Kronen\x02Neuseeland-Dollar\x02Polnische Złoty\x02Rumänische Leu" +
	"\x02Serbische Dinar\x02Schwedische Kronen\x02Taiwan-Dollar\x02US-Dollar" +
	"\x02Hier kannst du Gutscheine für Privatsphäre-freundliche Dienste kaufe" +
	"n und anonym mit Monero, Bitcoin oder Bargeld bezahlen. SEPA-Banküberwei" +
	"sung ist auch verfügbar.\x02Bestelle mit wenigen Klicks. Bezahle mit Mon" +
	"ero, Bitcoin, Bargeld in 20 Währungen, oder SEPA-Banküberweisung.\x02Wei" +
	"terlesen\x02Wähle die gewünschte Anzahl aus und klicke „Kaufen“.\x02Spei" +
	"chere deine Bestellung als Lesezeichen. Du brauchst sie, um auf die Code" +
	"s zuzugreifen.\x02Bezahle deine Bestellung.\x02Unbezahlte Bestellungen w" +
	"erden nach 30 Tagen gelöscht.\x02Monero (XMR) oder Bitcoin (BTC): Deine " +
	"Gutscheincodes werden angezeigt, sobald deine Zahlung in der Blockchain " +
	"bestätigt ist.\x02Bargeld: Schicke Bargeld (wir akzeptieren 20 Währungen" +
	") an unsere Adresse in Deutschland. Wir schreddern den Brief nach dem Fr" +
	"eischalten.\x02SEPA-Überweisung auf unser deutsches Bankkonto. Wir prüfe" +
	"n es täglich manuell auf neue Zahlungseingänge.\x02Optional: Lass dich p" +
	"er E-Mail oder ntfy.sh benachrichtigen, wenn deine Zahlung eintrifft." +
	"\x02Notiere dir die Codes. Wir werden sie 30 Tage nach der Auslieferung " +
	"löschen.\x02Bitte wähle eines oder mehrere Produkte aus.\x02vorrätig\x02" +
	"In welchem Land bist du ansässig? (Das müssen wir aus steuerlichen Gründ" +
	"en fragen. Es hat keinen Einfluss auf den Preis oder die Leistung.)\x02A" +
	"ußerhalb der Europäischen Union\x02Europäische Union\x02bitte auswählen" +
	"\x02Bitte wähle das Land aus, in dem du wohnst.\x02Die Länderoptionen hä" +
	"ngen von deiner IP-Adresse und Spracheinstellung ab.\x02Kaufen\x02Bestel" +
	"lung\x02Status\x02Derzeitiges Löschdatum\x02Du hast JavaScript deaktivie" +
	"rt. Um über Neuigkeiten informiert zu werden, lade die Seite bitte geleg" +
	"entlich neu.\x02Wie geht es weiter?\x02Setze diese Seite als Lesezeichen" +
	" oder speichere ihre Adresse anderweitig. Du brauchst sie, um auf die Co" +
	"des zuzugreifen.\x02Anklicken zum Kopieren\x02Bezahle deine Bestellung. " +
	"Unbezahlte Bestellungen werden nach 30 Tagen gelöscht.\x02Sobald deine Z" +
	"ahlung bei uns eintrifft, werden dir deine Gutscheincodes angezeigt. In " +
	"seltenen Fällen kann es passieren, dass das Produkt zwischenzeitlich aus" +
	"verkauft ist. Dann werden dir die Codes angezeigt, sobald Nachschub da i" +
	"st.\x02Zahlung\x02Optional: Lass dich benachrichtigen, wenn deine Zahlun" +
	"g eintrifft\x02Lass dich benachrichtigen, wenn deine Zahlung eingegangen" +
	" ist und die Voucher-Codes angezeigt werden. Die Benachrichtigung wird w" +
	"eder die Bestellnummer noch den Link enthalten. Deine Kontaktdaten werde" +
	"n danach gelöscht.\x02Wähle aus\x02E-Mail\x02Addresse\x02Speichern\x02De" +
	"ine Bestellung\x02Produkt\x02Anzahl\x02Einzelpreis\x02Summe\x02Gesamtsum" +
	"me\x02Deine Ware\x02Lieferdatum\x02Code\x02Die fehlenden Codes erhälst d" +
	"u, sobald Nachschub eintroffen ist. Wir bitten die Umstände zu entschuld" +
	"igen.\x02Sobald deine Zahlung bei uns eingegangen ist, erhälst du die Co" +
	"des.\x02Rechtliches\x02AGB\x02Datenschutz\x02Impressum\x02Widerrufsbeleh" +
	"rung\x02Bargeld per Post in 20 Währungen\x02Monero und Bitcoin\x02SEPA-B" +
	"anküberweisung\x02Alle Angebote und Projekte\x02Warum?\x02Ladengeschäft" +
	"\x02Digitale Güter\x02Onlineshop\x02Bestellservice\x02Onlinedruckerei" +
	"\x02Kontakt & News\x02Kontakt\x02Öffnungszeiten\x02Mo+Do 14-18 Uhr\x02Di" +
	"+Mi+Fr+Sa 10-14 Uhr\x02Sieh hier für kurzfristige Änderungen\x02Fehler o" +
	"der Hinweise? Schreib uns!\x02Bezahle den angegebenen Betrag in Monero (" +
	"XMR) oder Bitcoin (BTC). Der Betrag muss innerhalb von 60 Minuten vollst" +
	"ändig und als einzelne Transaktion auf der angegebenen Adresse eingehen" +
	". Falls deine Zahlung verspätet eintrifft, müssen wir sie manuell bestät" +
	"igen. Im Zweifel kontaktiere uns bitte.\x02Zur Bezahlung mit Monero oder" +
	" Bitcoin\x02Sende uns Bargeld in einem versichertem Brief oder Paket. Na" +
	"chdem wir das Geld entnommen haben, schreddern wir den Brief. Bitte beac" +
	"hte die Höchstgrenzen deines Postunternehmens für den Bargeldversand (z." +
	" B. Deutsche Post „Einschreiben Wert“ bis 100 Euro innerhalb Deutschland" +
	"s, DHL Paket bis 500 Euro). Sende es an:\x02Bitte lege einen Zettel mit " +
	"der Bestellnummer bei\x02Zahle den angegebenen Betrag in einer der folge" +
	"nden Währungen.\x02Bitte sende nur Banknoten und runde gegebenenfalls au" +
	"f. Wir nehmen keine Münzen an.\x02Betrag\x02Währung\x02%.2f\x02Falls du " +
	"Münzen sendest, klebe sie bitte gut fest. Sonst werden sie beim Transpor" +
	"t herausgedrückt.\x02Wir übermitteln nur die Bestellnummer an PayPal. De" +
	"ine bestellten Artikel sowie die Details zu Lieferung oder Abholung werd" +
	"en nicht an PayPal gesendet.\x02Falls du TOR oder einen VPN benutzt: Die" +
	" angezeigten Bezahlmöglichkeiten sind von der Länderzuordnung deiner IP-" +
	"Adresse abhängig. Darüber hinaus blockiert PayPal manche TOR Exit Nodes." +
	" In dem Fall versuche es mit „New Circuit for this Site“.\x02Überweise d" +
	"as Geld auf unser deutsches SEPA-Bankkonto. Wir prüfen es täglich manuel" +
	"l auf neue Zahlungseingänge. Wir werden deinen Namen und deine Kontonumm" +
	"er auf unserem Kontoauszug sehen. Falls dein Konto außerhalb des einheit" +
	"lichen Euro-Zahlungsverkehrsraums (SEPA) liegt, zahle eventuelle Gebühre" +
	"n bitte selbst, indem du die Gebührenregelung „OUR“ wählst.\x02Kontoinha" +
	"ber\x02IBAN\x02BIC (falls nötig)\x02Bank (falls nötig)\x02%.2f €\x02Über" +
	"weisungszweck\x02Oder scanne den EPC-QR-Code:"

var en_USIndex = []uint32{ // 159 elements
	// Entry 0 - 1F
	0x00000000, 0x00000021, 0x0000008e, 0x0000012d,
	0x0000014d, 0x00000151, 0x00000164, 0x00000173,
	0x0000017d, 0x000001b8, 0x000001ea, 0x00000234,
	0x00000274, 0x000002c0, 0x000002f3, 0x0000032c,
	0x00000334, 0x0000033c, 0x00000345, 0x00000351,
	0x00000358, 0x00000360, 0x00000368, 0x00000370,
	0x00000378, 0x0000037e, 0x00000386, 0x0000038d,
	0x0000039c, 0x000003a3, 0x000003ab, 0x000003b3,
	// Entry 20 - 3F
	0x000003bb, 0x000003c1, 0x000003cb, 0x000003d6,
	0x000003dd, 0x000003e8, 0x000003ee, 0x000003fa,
	0x00000401, 0x0000040a, 0x00000412, 0x00000419,
	0x00000422, 0x0000042b, 0x0000043d, 0x00000456,
	0x0000045b, 0x0000047d, 0x00000490, 0x0000049e,
	0x000004af, 0x000004bc, 0x000004cd, 0x000004da,
	0x000004e7, 0x000004f6, 0x00000507, 0x00000514,
	0x0000052d, 0x0000053d, 0x00000551, 0x0000055f,
	// Entry 40 - 5F
	0x0000056c, 0x0000057a, 0x00000588, 0x0000059b,
	0x000005b1, 0x0000064f, 0x000006b0, 0x000006ba,
	0x000006e2, 0x0000071e, 0x0000072e, 0x00000757,
	0x000007cb, 0x00000835, 0x000008ae, 0x000008f4,
	0x00000937, 0x00000954, 0x0000095d, 0x000009c2,
	0x000009dc, 0x000009eb, 0x000009f9, 0x00000a22,
	0x00000a67, 0x00000a6b, 0x00000a71, 0x00000a78,
	0x00000a8e, 0x00000b0c, 0x00000b19, 0x00000b77,
	// Entry 60 - 7F
	0x00000b85, 0x00000bbe, 0x00000c82, 0x00000c8a,
	0x00000cbb, 0x00000d79, 0x00000d80, 0x00000d86,
	0x00000d8e, 0x00000d93, 0x00000d9e, 0x00000da6,
	0x00000daf, 0x00000dba, 0x00000dbe, 0x00000dca,
	0x00000dd5, 0x00000de3, 0x00000de8, 0x00000e51,
	0x00000e91, 0x00000e97, 0x00000eac, 0x00000ebb,
	0x00000ec3, 0x00000ed7, 0x00000ef5, 0x00000f08,
	0x00000f1b, 0x00000f35, 0x00000f3a, 0x00000f46,
	// Entry 80 - 9F
	0x00000f54, 0x00000f60, 0x00000f6e, 0x00000f7e,
	0x00000f8d, 0x00000f98, 0x00000fa6, 0x00000fb6,
	0x00000fcf, 0x00000fef, 0x0000101e, 0x00001107,
	0x00001123, 0x00001253, 0x00001280, 0x000012bd,
	0x0000130b, 0x00001312, 0x0000131b, 0x00001320,
	0x0000138e, 0x00001405, 0x000014c9, 0x00001615,
	0x00001624, 0x00001629, 0x0000163b, 0x00001653,
	0x0000165c, 0x00001664, 0x0000167d,
} // Size: 660 bytes

const en_USData string = "" + // Size: 5757 bytes
	"\x02We are waiting for your payment.\x02A payment is on the way, but we'" +
	"re still waiting for the required amount of confirmations on the blockch" +
	"ain.\x02We have received your payment, but have gone out of stock meanwh" +
	"ile. You will receive the missing codes here as soon as possible. Sorry " +
	"for the inconvenience.\x02Your codes have been delivered.\x02New\x02Paym" +
	"ent processing\x02Underdelivered\x02Finalized\x02Error getting stock fro" +
	"m database. Please try again later.\x02Error displaying website. Please " +
	"try again later.\x02Our service thinks that you are a bot. If you are no" +
	"t, please contact us.\x02Error inserting purchase into database. Please " +
	"try again later.\x02There is no such purchase, or it has been deleted, o" +
	"r the URL is incorrect.\x02There is no such purchase, or it has been del" +
	"eted.\x02Error saving notify information. Please try again later.\x02Aus" +
	"tria\x02Belgium\x02Bulgaria\x02Switzerland\x02Cyprus\x02Czechia\x02Germa" +
	"ny\x02Denmark\x02Estonia\x02Spain\x02Finland\x02France\x02United Kingdom" +
	"\x02Greece\x02Croatia\x02Hungary\x02Ireland\x02Italy\x02Lithuania\x02Lux" +
	"embourg\x02Latvia\x02Montenegro\x02Malta\x02Netherlands\x02Poland\x02Por" +
	"tugal\x02Romania\x02Sweden\x02Slovenia\x02Slovakia\x02Monero or Bitcoin" +
	"\x02Cash in Foreign Currency\x02Cash\x02Bank Transfer to our SEPA Accoun" +
	"t\x02Australian dollars\x02Bulgarian lev\x02Canadian dollars\x02Swiss fr" +
	"ancs\x02Chinese renminbi\x02Czech koruna\x02Danish krone\x02Pound sterli" +
	"ng\x02Icelandic króna\x02Japanese yen\x02New Israeli shekel (NIS)\x02Nor" +
	"wegian krone\x02New Zealand dollars\x02Polish złoty\x02Romanian leu\x02S" +
	"erbian dinar\x02Swedish krona\x02New Taiwan dollars\x02United States dol" +
	"lars\x02Buy coupons, voucher codes and gift cards for privacy services a" +
	"nd pay anonymously with Monero, Bitcoin or cash letter. SEPA Bank transf" +
	"er is also available.\x02Order with a few clicks. Pay with Monero, Bitco" +
	"in, cash in 20 currencies, or SEPA Bank transfer.\x02Read more\x02Enter " +
	"the quantity and press „Buy“.\x02Bookmark your order. You will need it t" +
	"o access your goods.\x02Pay your order.\x02Unpaid orders are deleted aft" +
	"er 30 days.\x02Monero (XMR) or Bitcoin (BTC): Your voucher codes are sho" +
	"wn as soon as your payment is confirmed on the blockchain.\x02Cash: Send" +
	" cash (we accept 20 currencies) to our office in Germany. We shred the l" +
	"etter after processing.\x02SEPA (Single Euro Payments Area) bank transfe" +
	"r to our German bank account. We manually check for new payments every d" +
	"ay.\x02Optional: Get notified by email or ntfy.sh when your payment arri" +
	"ves.\x02Write down your codes. We will delete them 30 days after deliver" +
	"y.\x02Please select some products.\x02in stock\x02Where do you live? (We" +
	" have to ask that for tax reasons. It does not affect the price or the g" +
	"oods.)\x02Not in the European Union\x02European Union\x02please select" +
	"\x02Please select your country of residence.\x02Country options are limi" +
	"ted by your IP address and browser language.\x02Buy\x02Order\x02Status" +
	"\x02Current deletion date\x02JavaScript is disabled in your browser. In " +
	"order to receive updates on your order, please reload this page from tim" +
	"e to time.\x02What's next?\x02Bookmark this page or save its address in " +
	"another way. You will need it to access your goods.\x02Click to copy\x02" +
	"Pay your order. Unpaid orders are deleted after 30 days.\x02As soon as y" +
	"our payment arrives, your voucher codes are shown. In the unlikely case " +
	"that your goods have become sold out in the meantime, your codes will ap" +
	"pear as soon as they are back in stock.\x02Payment\x02Optional: Get noti" +
	"fied when your payment arrives\x02Get notified when your payment arrives" +
	" and your voucher codes are shown. The notification will not contain the" +
	" order number or the link. Your contact information will be deleted afte" +
	"rwards.\x02Select\x02Email\x02Address\x02Save\x02Your Order\x02Product" +
	"\x02Quantity\x02Item Price\x02Sum\x02Overall Sum\x02Your Goods\x02Delive" +
	"ry Date\x02Code\x02You will receive the missing codes here as soon as th" +
	"ey are in stock again. Sorry for the inconvenience.\x02You will receive " +
	"your codes as soon as you payment has arrived.\x02Legal\x02Terms and Con" +
	"ditions\x02Privacy policy\x02Imprint\x02Cancellation Policy\x02Cash by m" +
	"ail in 20 currencies\x02Monero and Bitcoin\x02SEPA bank transfer\x02All " +
	"Services and Projects\x02Why?\x02Local Store\x02Digital Goods\x02Online " +
	"shop\x02Order Service\x02Online printing\x02Contact & News\x02Contact us" +
	"\x02Opening hours\x02Mon+Thu 2pm-6pm\x02Tue+Wed+Fri+Sat 10am-2pm\x02See " +
	"here for short-term changes\x02Got an idea or found an error? Drop us a " +
	"note!\x02Pay with Monero (XMR) or Bitcoin (BTC). The full amount must be" +
	" paid with a single transaction to the given address within 60 minutes. " +
	"If your payment arrives too late, we have to confirm it manually. If in " +
	"doubt, please contact us.\x02Pay using Monero or Bitcoin\x02Send cash in" +
	" an insured letter or package to our store address in Germany. After we " +
	"take out the money, we shred the letter. Please check the cash shipment " +
	"limits of your postal company (e. g. Deutsche Post „Einschreiben Wert“ u" +
	"p to 100 Euros within Germany, DHL Parcel up to 500 Euros). Send it to:" +
	"\x02Please include a note with this order number\x02Pay the specified am" +
	"ount in one of the following currencies.\x02Please send banknotes only a" +
	"nd round up if necessary. We do not accept coins.\x02Amount\x02Currency" +
	"\x02%.2f\x02If you are sending coins, please stick them down firmly. Oth" +
	"erwise they will be pressed out during transport.\x02We only send the or" +
	"der number to PayPal. Your ordered items and delivery or pickup details " +
	"will not be sent to PayPal.\x02If you use TOR or a VPN: The payment opti" +
	"ons displayed depend on the country of your IP address. In addition, Pay" +
	"Pal blocks some TOR exit nodes. In that case, try „New Circuit for this " +
	"Site“.\x02Make a bank transfer to our German SEPA (Single Euro Payments " +
	"Area) bank account. We check for new incoming payments manually every da" +
	"y. We will see your name and account number on our bank statement. If yo" +
	"ur bank account is outside the Single Euro Payments Area, please pay any" +
	" fees yourself by selecting the „OUR“ fee option.\x02Account holder\x02I" +
	"BAN\x02BIC (if required)\x02Bank name (if required)\x02%.2f EUR\x02Purpo" +
	"se\x02Or scan the EPC QR code:"

	// Total table size 13799 bytes (13KiB); checksum: ECF49D75
