// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package html

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"A payment is on the way, but we're still waiting for the required amount of confirmations on the blockchain.": 1,
	"Amount": 70,
	"As soon as your payment arrives, your voucher codes are shown. In the unlikely case that your goods have become sold out in the meantime, your codes will appear as soon as they are back in stock.": 66,
	"Australian dollars":       41,
	"Austria":                  8,
	"Belgium":                  9,
	"Bulgaria":                 10,
	"Bulgarian lev":            42,
	"Canadian dollars":         43,
	"Cash":                     39,
	"Cash in Foreign Currency": 38,
	"Cash: Send an insured letter or package with cash to our office in Germany. We shred the letter after processing.": 64,
	"Check your order.":     85,
	"Chinese renminbi":      45,
	"Code":                  93,
	"Create order":          79,
	"Croatia":               22,
	"Current deletion date": 82,
	"Cyprus":                12,
	"Czech koruna":          46,
	"Czechia":               13,
	"Danish krone":          47,
	"Delivery Date":         92,
	"Denmark":               15,
	"Enter the amount and press „Order“.": 60,
	"Estonia":               16,
	"European Union":        77,
	"Finalized":             7,
	"Finland":               18,
	"France":                19,
	"Germany":               14,
	"Greece":                21,
	"Hungary":               23,
	"Icelandic króna":       49,
	"In Stock":              71,
	"Internal server error": 96,
	"Ireland":               24,
	"Italy":                 25,
	"Item Price":            72,
	"Japanese yen":          50,
	"JavaScript is disabled in your browser. In order to receive updates on your order, please reload this page from time to time.": 83,
	"Latvia":     28,
	"Lithuania":  26,
	"Luxembourg": 27,
	"Malta":      29,
	"Monero (XMR) or Bitcoin (BTC): The fastest method. Your voucher codes are shown as soon as your payment is confirmed on the blockchain.": 63,
	"Monero or Bitcoin":         37,
	"Netherlands":               30,
	"New":                       4,
	"New Israeli shekel (NIS)":  51,
	"New Taiwan dollars":        58,
	"New Zealand dollars":       53,
	"Norwegian krone":           52,
	"Not in the European Union": 75,
	"Order":                     80,
	"Overall Sum":               90,
	"Pay your order using one of these methods. (Unpaid orders are deleted after 30 days.)": 62,
	"Pay your order. (Unpaid orders are deleted after 30 days.)":                            86,
	"Payment":                                87,
	"Payment processing":                     5,
	"Please select a country from the list.": 78,
	"Please select some products.":           68,
	"Poland":                                 31,
	"Polish złoty":                           54,
	"Portugal":                               32,
	"Pound sterling":                         48,
	"Product":                                69,
	"Romania":                                33,
	"Romanian leu":                           55,
	"SEPA (Single Euro Payments Area) bank transfer to our German bank account. We manually check for new incoming payments every day.": 65,
	"SEPA Bank Transfer": 40,
	"Save the URL of your order. You need it to access your goods if you closed the browser tab.": 61,
	"Serbian dinar": 56,
	"Slovakia":      36,
	"Slovenia":      35,
	"Spain":         17,
	"Status":        81,
	"Sum":           89,
	"Sweden":        34,
	"Swedish krona": 57,
	"Swiss francs":  44,
	"Switzerland":   11,
	"There is no such order, or it has been deleted.": 97,
	"Underdelivered":                   6,
	"United Kingdom":                   20,
	"United States dollars":            59,
	"We are waiting for your payment.": 0,
	"We have received your payment, but have gone out of stock meanwhile. You will receive the missing codes here as soon as possible. Sorry for the inconvenience.": 2,
	"What's next?": 84,
	"Where do you live? (We have to ask that for tax reasons. It does not affect the price or the goods.)":     74,
	"Write down your codes. We will delete them 30 days after delivery.":                                       67,
	"You will receive the missing codes here as soon as they are in stock again. Sorry for the inconvenience.": 94,
	"You will receive your codes as soon as you payment has arrived.":                                          95,
	"Your Goods":                      91,
	"Your Order":                      88,
	"Your codes have been delivered.": 3,
	"click here to read more":         73,
	"non-EU":                          76,
}

var de_DEIndex = []uint32{ // 99 elements
	// Entry 0 - 1F
	0x00000000, 0x0000002b, 0x000000a1, 0x00000155,
	0x00000176, 0x0000017a, 0x00000193, 0x000001a2,
	0x000001b0, 0x000001bc, 0x000001c4, 0x000001ce,
	0x000001d6, 0x000001dd, 0x000001e8, 0x000001f4,
	0x000001fe, 0x00000206, 0x0000020e, 0x00000217,
	0x00000222, 0x0000023a, 0x00000247, 0x00000250,
	0x00000257, 0x0000025e, 0x00000266, 0x0000026e,
	0x00000278, 0x00000281, 0x00000287, 0x00000293,
	// Entry 20 - 3F
	0x00000299, 0x000002a2, 0x000002ac, 0x000002b5,
	0x000002bf, 0x000002c8, 0x000002dc, 0x000002f5,
	0x000002fd, 0x00000313, 0x00000327, 0x00000337,
	0x00000349, 0x0000035b, 0x00000370, 0x00000384,
	0x00000395, 0x000003a5, 0x000003b9, 0x000003c8,
	0x000003e7, 0x000003fa, 0x0000040c, 0x0000041d,
	0x0000042d, 0x0000043d, 0x00000450, 0x0000045e,
	0x00000468, 0x000004a6, 0x00000532, 0x000005a0,
	// Entry 40 - 5F
	0x00000637, 0x000006c9, 0x00000736, 0x00000821,
	0x0000086f, 0x0000089d, 0x000008a5, 0x000008ac,
	0x000008b6, 0x000008c2, 0x000008de, 0x0000096d,
	0x00000990, 0x00000997, 0x000009aa, 0x000009d3,
	0x000009dd, 0x000009e8, 0x000009ef, 0x00000a07,
	0x00000a79, 0x00000a8d, 0x00000aa6, 0x00000b14,
	0x00000b1c, 0x00000b2d, 0x00000b33, 0x00000b3f,
	0x00000b4a, 0x00000b56, 0x00000b5b, 0x00000bc8,
	// Entry 60 - 7F
	0x00000c0d, 0x00000c23, 0x00000c60,
} // Size: 420 bytes

const de_DEData string = "" + // Size: 3168 bytes
	"\x02Wir warten auf den Eingang deiner Zahlung.\x02Eine Zahlung wurde ang" +
	"ekündigt, aber wir warten noch auf die erforderliche Anzahl Bestätigunge" +
	"n auf der Blockchain.\x02Wir haben deine Zahlung erhalten, aber unser Vo" +
	"rrat wurde zwischenzeitlich ausverkauft. Die fehlenden Codes erhälst du " +
	"möglichst bald. Wir bitten die Umstände zu entschuldigen.\x02Deine Codes" +
	" wurden ausgeliefert.\x02Neu\x02Zahlung wird verarbeitet\x02Unterbeliefe" +
	"rt\x02Abgeschlossen\x02Österreich\x02Belgien\x02Bulgarien\x02Schweiz\x02" +
	"Zypern\x02Tschechien\x02Deutschland\x02Dänemark\x02Estland\x02Spanien" +
	"\x02Finnland\x02Frankreich\x02Vereinigtes Königreich\x02Griechenland\x02" +
	"Kroatien\x02Ungarn\x02Irland\x02Italien\x02Litauen\x02Luxemburg\x02Lettl" +
	"and\x02Malta\x02Niederlande\x02Polen\x02Portugal\x02Rumänien\x02Schweden" +
	"\x02Slowenien\x02Slowakei\x02Monero oder Bitcoin\x02Bargeld in Fremdwähr" +
	"ung\x02Bargeld\x02SEPA-Banküberweisung\x02Australische Dollar\x02Bulgari" +
	"sche Lew\x02Kanadische Dollar\x02Schweizer Franken\x02Chinesische Renmin" +
	"bi\x02Tschechische Kronen\x02Dänische Kronen\x02Britische Pfund\x02Islän" +
	"dische Kronen\x02Japanische Yen\x02Neue israelische Schekel (NIS)\x02Nor" +
	"wegische Kronen\x02Neuseeland-Dollar\x02Polnische Złoty\x02Rumänische Le" +
	"u\x02Serbische Dinar\x02Schwedische Kronen\x02Taiwan-Dollar\x02US-Dollar" +
	"\x02Wähle die gewünschte Anzahl aus und klicke „Bestellen“.\x02Speichere" +
	" die Webadresse deiner Bestellung. Du brauchst sie, um auf deine Güter z" +
	"uzugreifen, falls du das Browserfenster geschlossen hast.\x02Bezahle dei" +
	"ne Bestellung mit einer dieser Methoden. (Unbezahlte Bestellungen werden" +
	" nach 30 Tagen gelöscht.)\x02Monero (XMR) oder Bitcoin (BTC): Die schnel" +
	"lste Methode. Deine Gutscheincodes werden angezeigt, sobald deine Zahlun" +
	"g in der Blockchain bestätigt ist.\x02Bargeld: Schicke Bargeld in einem " +
	"versichertem Brief oder Paket an unsere Adresse in Deutschland. Wir schr" +
	"eddern den Brief nach dem Freischalten.\x02SEPA-Überweisung auf unser de" +
	"utsches Bankkonto. Wir prüfen es täglich manuell auf neue Zahlungseingän" +
	"ge.\x02Sobald deine Zahlung bei uns eintrifft, werden dir deine Gutschei" +
	"ncodes angezeigt. In seltenen Fällen kann es passieren, dass das Produkt" +
	" zwischenzeitlich ausverkauft ist. Dann werden dir die Codes angezeigt, " +
	"sobald Nachschub da ist.\x02Notiere dir die Codes. Wir werden sie 30 Tag" +
	"e nach der Auslieferung löschen.\x02Bitte wähle eines oder mehrere Produ" +
	"kte aus.\x02Produkt\x02Anzahl\x02Vorrätig\x02Einzelpreis\x02klicke hier " +
	"für mehr Infos\x02In welchem Land bist du ansässig? (Das müssen wir aus " +
	"steuerlichen Gründen fragen. Es hat keinen Einfluss auf den Preis oder d" +
	"ie Leistung.)\x02Außerhalb der Europäischen Union\x02non-EU\x02Europäisc" +
	"he Union\x02Bitte wähle ein Land aus der Liste aus.\x02Bestellen\x02Best" +
	"ellung\x02Status\x02Derzeitiges Löschdatum\x02Du hast JavaScript deaktiv" +
	"iert. Um über Neuigkeiten informiert zu werden, lade die Seite bitte gel" +
	"egentlich neu.\x02Wie geht es weiter?\x02Prüfe deine Bestellung.\x02Beza" +
	"hle deine Bestellung mit einer dieser Methoden. (Unbezahlte Bestellungen" +
	" werden nach 30 Tagen gelöscht.)\x02Zahlung\x02Deine Bestellung\x02Summe" +
	"\x02Gesamtsumme\x02Deine Ware\x02Lieferdatum\x02Code\x02Die fehlenden Co" +
	"des erhälst du, sobald Nachschub eintroffen ist. Wir bitten die Umstände" +
	" zu entschuldigen.\x02Sobald deine Zahlung bei uns eingegangen ist, erhä" +
	"lst du die Codes.\x02Interner Serverfehler\x02Diese Bestellung existiert" +
	" nicht oder wurde schon gelöscht."

var en_USIndex = []uint32{ // 99 elements
	// Entry 0 - 1F
	0x00000000, 0x00000021, 0x0000008e, 0x0000012d,
	0x0000014d, 0x00000151, 0x00000164, 0x00000173,
	0x0000017d, 0x00000185, 0x0000018d, 0x00000196,
	0x000001a2, 0x000001a9, 0x000001b1, 0x000001b9,
	0x000001c1, 0x000001c9, 0x000001cf, 0x000001d7,
	0x000001de, 0x000001ed, 0x000001f4, 0x000001fc,
	0x00000204, 0x0000020c, 0x00000212, 0x0000021c,
	0x00000227, 0x0000022e, 0x00000234, 0x00000240,
	// Entry 20 - 3F
	0x00000247, 0x00000250, 0x00000258, 0x0000025f,
	0x00000268, 0x00000271, 0x00000283, 0x0000029c,
	0x000002a1, 0x000002b4, 0x000002c7, 0x000002d5,
	0x000002e6, 0x000002f3, 0x00000304, 0x00000311,
	0x0000031e, 0x0000032d, 0x0000033e, 0x0000034b,
	0x00000364, 0x00000374, 0x00000388, 0x00000396,
	0x000003a3, 0x000003b1, 0x000003bf, 0x000003d2,
	0x000003e8, 0x00000410, 0x0000046c, 0x000004c2,
	// Entry 40 - 5F
	0x0000054a, 0x000005bc, 0x0000063e, 0x00000702,
	0x00000745, 0x00000762, 0x0000076a, 0x00000771,
	0x0000077a, 0x00000785, 0x0000079d, 0x00000802,
	0x0000081c, 0x00000823, 0x00000832, 0x00000859,
	0x00000866, 0x0000086c, 0x00000873, 0x00000889,
	0x00000907, 0x00000914, 0x00000926, 0x00000961,
	0x00000969, 0x00000974, 0x00000978, 0x00000984,
	0x0000098f, 0x0000099d, 0x000009a2, 0x00000a0b,
	// Entry 60 - 7F
	0x00000a4b, 0x00000a61, 0x00000a91,
} // Size: 420 bytes

const en_USData string = "" + // Size: 2705 bytes
	"\x02We are waiting for your payment.\x02A payment is on the way, but we'" +
	"re still waiting for the required amount of confirmations on the blockch" +
	"ain.\x02We have received your payment, but have gone out of stock meanwh" +
	"ile. You will receive the missing codes here as soon as possible. Sorry " +
	"for the inconvenience.\x02Your codes have been delivered.\x02New\x02Paym" +
	"ent processing\x02Underdelivered\x02Finalized\x02Austria\x02Belgium\x02B" +
	"ulgaria\x02Switzerland\x02Cyprus\x02Czechia\x02Germany\x02Denmark\x02Est" +
	"onia\x02Spain\x02Finland\x02France\x02United Kingdom\x02Greece\x02Croati" +
	"a\x02Hungary\x02Ireland\x02Italy\x02Lithuania\x02Luxembourg\x02Latvia" +
	"\x02Malta\x02Netherlands\x02Poland\x02Portugal\x02Romania\x02Sweden\x02S" +
	"lovenia\x02Slovakia\x02Monero or Bitcoin\x02Cash in Foreign Currency\x02" +
	"Cash\x02SEPA Bank Transfer\x02Australian dollars\x02Bulgarian lev\x02Can" +
	"adian dollars\x02Swiss francs\x02Chinese renminbi\x02Czech koruna\x02Dan" +
	"ish krone\x02Pound sterling\x02Icelandic króna\x02Japanese yen\x02New Is" +
	"raeli shekel (NIS)\x02Norwegian krone\x02New Zealand dollars\x02Polish z" +
	"łoty\x02Romanian leu\x02Serbian dinar\x02Swedish krona\x02New Taiwan do" +
	"llars\x02United States dollars\x02Enter the amount and press „Order“." +
	"\x02Save the URL of your order. You need it to access your goods if you " +
	"closed the browser tab.\x02Pay your order using one of these methods. (U" +
	"npaid orders are deleted after 30 days.)\x02Monero (XMR) or Bitcoin (BTC" +
	"): The fastest method. Your voucher codes are shown as soon as your paym" +
	"ent is confirmed on the blockchain.\x02Cash: Send an insured letter or p" +
	"ackage with cash to our office in Germany. We shred the letter after pro" +
	"cessing.\x02SEPA (Single Euro Payments Area) bank transfer to our German" +
	" bank account. We manually check for new incoming payments every day." +
	"\x02As soon as your payment arrives, your voucher codes are shown. In th" +
	"e unlikely case that your goods have become sold out in the meantime, yo" +
	"ur codes will appear as soon as they are back in stock.\x02Write down yo" +
	"ur codes. We will delete them 30 days after delivery.\x02Please select s" +
	"ome products.\x02Product\x02Amount\x02In Stock\x02Item Price\x02click he" +
	"re to read more\x02Where do you live? (We have to ask that for tax reaso" +
	"ns. It does not affect the price or the goods.)\x02Not in the European U" +
	"nion\x02non-EU\x02European Union\x02Please select a country from the lis" +
	"t.\x02Create order\x02Order\x02Status\x02Current deletion date\x02JavaSc" +
	"ript is disabled in your browser. In order to receive updates on your or" +
	"der, please reload this page from time to time.\x02What's next?\x02Check" +
	" your order.\x02Pay your order. (Unpaid orders are deleted after 30 days" +
	".)\x02Payment\x02Your Order\x02Sum\x02Overall Sum\x02Your Goods\x02Deliv" +
	"ery Date\x02Code\x02You will receive the missing codes here as soon as t" +
	"hey are in stock again. Sorry for the inconvenience.\x02You will receive" +
	" your codes as soon as you payment has arrived.\x02Internal server error" +
	"\x02There is no such order, or it has been deleted."

	// Total table size 6713 bytes (6KiB); checksum: 78835E9F
